#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
BIN="${HERE}/usr/bin"
EXEC="${BIN}/SuperPatcherGSI.py"

while getopts ":i:o:s:h" o; do
    case "${o}" in
        i)
            INPUT=${OPTARG}
            ;;
        o)
            OUTPUT=${OPTARG}
            ;;
        s)
            SLOT=${OPTARG}
            ;;
        h)
            echo "usage: SuperPatcherGSI.py [-i INPUT] [-o OUTPUT] [-g GSI] [-s SLOT]

options:
  -h, --help (optional) displays all flags and there purpose
  -i INPUT
                        input the super.img that is going to be modifed, if super.img is sparse its going to
                        temporarily be unsparsed
  -o OUTPUT
                        Directs the output to a name of your choice
  -s SLOT               
                        number of slots on the device can only be 1 (A) or 2 (A/B)" ; exit 1
            ;;
    esac
done

exec python3 "${EXEC}" -i "${INPUT}" -o "${OUTPUT}" -s "${SLOT}"